#if !canImport(ObjectiveC)
import XCTest

extension FileAndURLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileAndURLTests = [
        ("testAppendQueryItemToURL", testAppendQueryItemToURL),
        ("testCannonicalPath", testCannonicalPath),
        ("testShellScripting", testShellScripting),
        ("testURLLastPathName", testURLLastPathName),
        ("testURLResolveAlias", testURLResolveAlias),
    ]
}

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testJSONAndTempDir", testJSONAndTempDir),
    ]
}

extension LazySequenceExtensions {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LazySequenceExtensions = [
        ("testSplitAndLines", testSplitAndLines),
    ]
}

extension MathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MathTests = [
        ("testComparisonOperators", testComparisonOperators),
        ("testExponentOperators", testExponentOperators),
        ("testFactorial", testFactorial),
        ("testNumbersAreClose", testNumbersAreClose),
    ]
}

extension MiscellaneousTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiscellaneousTests = [
        ("testAllAny", testAllAny),
        ("testTimeUnits", testTimeUnits),
    ]
}

extension NetworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NetworkTests = [
        ("testURLRequestDecodeJSON", testURLRequestDecodeJSON),
    ]
}

extension PropertyWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PropertyWrapperTests = [
        ("testPropertyWrapper", testPropertyWrapper),
        ("testPropertyWrapper2", testPropertyWrapper2),
        ("testPropertyWrapperDocs", testPropertyWrapperDocs),
    ]
}

extension SequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequenceTests = [
        ("testAnySequence", testAnySequence),
        ("testArrayChunking", testArrayChunking),
        ("testArrayNegativeIndexing", testArrayNegativeIndexing),
        ("testArraySafeIndexing", testArraySafeIndexing),
        ("testCollectionDuplicatesAndAppendUnique", testCollectionDuplicatesAndAppendUnique),
        ("testEquatableArrayDuplicates", testEquatableArrayDuplicates),
        ("testMutateEach", testMutateEach),
        ("testReduceFromFirstElement", testReduceFromFirstElement),
        ("testRemoveFirst", testRemoveFirst),
        ("testSequenceSum", testSequenceSum),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testRemoveFirstChar", testRemoveFirstChar),
        ("testStringFormatting", testStringFormatting),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FileAndURLTests.__allTests__FileAndURLTests),
        testCase(JSONTests.__allTests__JSONTests),
        testCase(LazySequenceExtensions.__allTests__LazySequenceExtensions),
        testCase(MathTests.__allTests__MathTests),
        testCase(MiscellaneousTests.__allTests__MiscellaneousTests),
        testCase(NetworkTests.__allTests__NetworkTests),
        testCase(PropertyWrapperTests.__allTests__PropertyWrapperTests),
        testCase(SequenceTests.__allTests__SequenceTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
