#if !canImport(ObjectiveC)
import XCTest

extension FileAndURLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileAndURLTests = [
        ("testAppendQueryItemToURL", testAppendQueryItemToURL),
        ("testCannonicalPath", testCannonicalPath),
        ("testShellScripting", testShellScripting),
        ("testURLLastPathName", testURLLastPathName),
        ("testURLResolveAlias", testURLResolveAlias),
    ]
}

extension IteratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IteratorTests = [
        ("testCIterator", testCIterator),
        ("testExponentiate", testExponentiate),
    ]
}

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testJSONAndTempDir", testJSONAndTempDir),
    ]
}

extension MathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MathTests = [
        ("testFactorial", testFactorial),
        ("testNumbersAreClose", testNumbersAreClose),
        ("testOperators", testOperators),
    ]
}

extension MiscellaneousTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiscellaneousTests = [
        ("testAllAny", testAllAny),
        ("testTimeUnits", testTimeUnits),
    ]
}

extension PropertyWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PropertyWrapperTests = [
        ("testPropertyWrapper", testPropertyWrapper),
    ]
}

extension SequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequenceTests = [
        ("testAnySequence", testAnySequence),
        ("testArrayChunking", testArrayChunking),
        ("testArrayNegativeIndexing", testArrayNegativeIndexing),
        ("testArraySafeIndexing", testArraySafeIndexing),
        ("testCollectionDuplicatesAndAppendUnique", testCollectionDuplicatesAndAppendUnique),
        ("testEquatableArrayDuplicates", testEquatableArrayDuplicates),
        ("testSequenceSum", testSequenceSum),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testExtendedGraphemeClusters", testExtendedGraphemeClusters),
        ("testGetStringByIndex", testGetStringByIndex),
        ("testPythonStringFormat", testPythonStringFormat),
        ("testSetStringByIndex", testSetStringByIndex),
        ("testStringFormatting", testStringFormatting),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FileAndURLTests.__allTests__FileAndURLTests),
        testCase(IteratorTests.__allTests__IteratorTests),
        testCase(JSONTests.__allTests__JSONTests),
        testCase(MathTests.__allTests__MathTests),
        testCase(MiscellaneousTests.__allTests__MiscellaneousTests),
        testCase(PropertyWrapperTests.__allTests__PropertyWrapperTests),
        testCase(SequenceTests.__allTests__SequenceTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
